export const ApiErrorCodes = [
  'AUTH_REQUIRED',
  'FORBIDDEN',
  'ITEM_NOT_FOUND',
  'ITEM_INVALID_STATE',
  'ITEM_VERSION_CONFLICT',
  'ITEM_UNAVAILABLE',
  'PROPOSAL_NOT_FOUND',
  'PROPOSAL_INVALID_STATE',
  'PROPOSAL_VERSION_CONFLICT',
  'PROPOSAL_EXPIRED',
  'PROPOSAL_WRONG_TURN',
  'PROPOSAL_SIDE_FORBIDDEN',
  'PROPOSAL_ALREADY_CONVERTED',
  'ORDER_NOT_FOUND',
  'ORDER_VERSION_CONFLICT',
  'ORDER_INVALID_STATE',
  'ORDER_EXPIRED',
  'ORDER_DETAILS_REQUIRED',
  'ORDER_PAYMENT_NOT_READY',
  'ORDER_FULFILLMENT_STARTED',
  'ORDER_CANCELLATION_PENDING',
  'ORDER_ON_HOLD',
  'ORDER_ALREADY_EXISTS',
  'TRACKING_NUMBER_IN_USE',
  'INTEGRATION_EVENT_INVALID',
  'INTEGRATION_UNAVAILABLE',
  'IDEMPOTENCY_CONFLICT',
  'IDENTITY_PROVIDER_UNAVAILABLE',
  'VALIDATION_FAILED',
] as const;

export type ApiErrorCode = (typeof ApiErrorCodes)[number];

export interface ApiErrorBody {
  code: ApiErrorCode;
  message: string;
  requestId: string;
  details?: unknown;
}
